---
version: "3"
services:
  db:
    container_name: db
    bulid: ./database/
    ports:
      - "3306:3306"
    networks:
      - my_net
  borrow:
    conatiner_name: borrow_service
    build: ./borrow/
    ports:
      - "5003:5003"
    networks:
      - my_net
  auth:
    container_name: auth_service
    build: ./auth/
    ports:
      - "5001:5001"
    networks:
      - my_net
  book:
    conatiner_name: book_service
    build: ./book/
    ports:
      - "5002:5002"
    networks:
      - my_net
  app:
    conatiner_name: application
    build: .
    ports:
      - "5000:5000"
    networks:
      - my_net


networks:
  my_net:
    driver: host

